import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import type { Metafile } from "esbuild";

type PackageMetadata = {
  license?: unknown;
  name?: unknown;
  version?: unknown;
};

type BundledPackage = {
  id: string;
  license?: string;
  notices: Array<{ name: string; text: string }>;
};

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function isNoticeFile(name: string): boolean {
  const normalized = name.toLowerCase();
  if (!/^(?:licen[cs]e|notice)(?:$|[-_.])/.test(normalized)) return false;
  return !/\.(?:cjs|js|json|jsx|map|mjs|ts|tsx)$/.test(normalized);
}

function normalizeNotice(text: string): string {
  return `${text.replaceAll("\r\n", "\n").replaceAll("\r", "\n").trimEnd()}\n`;
}

async function packageRootForInput(
  input: string,
  workingDirectory: string,
): Promise<string | undefined> {
  let candidate = path.dirname(
    path.isAbsolute(input) ? input : path.resolve(workingDirectory, input),
  );
  const root = path.parse(candidate).root;
  while (candidate !== root) {
    try {
      const metadata = JSON.parse(
        await readFile(path.join(candidate, "package.json"), "utf8"),
      ) as PackageMetadata;
      if (typeof metadata.name === "string" && typeof metadata.version === "string") {
        return candidate;
      }
    } catch {
      // Inputs commonly live several directories below their package manifest.
    }
    candidate = path.dirname(candidate);
  }
  return undefined;
}

export async function contributingPackageRoots(
  metafile: Metafile,
  workingDirectory: string,
): Promise<string[]> {
  const inputs = new Set<string>();
  for (const output of Object.values(metafile.outputs)) {
    for (const [input, contribution] of Object.entries(output.inputs)) {
      if (contribution.bytesInOutput > 0) inputs.add(input);
    }
  }

  const packageRoots = new Set<string>();
  for (const input of inputs) {
    if (input === "inkpath-mermaid-client.js") continue;
    const packageRoot = await packageRootForInput(input, workingDirectory);
    if (!packageRoot) throw new Error(`could not identify the package that contributed ${input}`);
    packageRoots.add(packageRoot);
  }
  return [...packageRoots].sort(compareText);
}

async function bundledPackages(packageRoots: Iterable<string>): Promise<BundledPackage[]> {
  const packages = new Map<string, BundledPackage>();
  for (const packageRoot of packageRoots) {
    const metadata = JSON.parse(
      await readFile(path.join(packageRoot, "package.json"), "utf8"),
    ) as PackageMetadata;
    if (typeof metadata.name !== "string" || typeof metadata.version !== "string") {
      throw new Error(`${packageRoot}: package name and version must be strings`);
    }

    const id = `${metadata.name}@${metadata.version}`;
    const entries = await readdir(packageRoot, { withFileTypes: true });
    const noticeNames = entries
      .filter((entry) => entry.isFile() && isNoticeFile(entry.name))
      .map((entry) => entry.name)
      .sort(compareText);
    if (!noticeNames.length) throw new Error(`${id}: package has no license or notice file`);

    const notices = await Promise.all(
      noticeNames.map(async (name) => ({
        name,
        text: normalizeNotice(await readFile(path.join(packageRoot, name), "utf8")),
      })),
    );
    const entry: BundledPackage = {
      id,
      ...(typeof metadata.license === "string" ? { license: metadata.license } : {}),
      notices,
    };
    const existing = packages.get(id);
    if (existing && JSON.stringify(existing) !== JSON.stringify(entry)) {
      throw new Error(`${id}: duplicate installations have different notices`);
    }
    packages.set(id, entry);
  }

  return [...packages.values()].sort((left, right) => compareText(left.id, right.id));
}

export async function renderThirdPartyNotices(packageRoots: Iterable<string>): Promise<string> {
  const packages = await bundledPackages(packageRoots);
  const sections = packages.map((entry) => {
    const notices = entry.notices
      .map((notice) => `${"-".repeat(80)}\n${notice.name}\n${"-".repeat(80)}\n${notice.text}`)
      .join("\n");
    const declaredLicense = entry.license ? `\nDeclared license: ${entry.license}` : "";
    return `${"=".repeat(80)}\n${entry.id}${declaredLicense}\n${"=".repeat(80)}\n\n${notices}`;
  });

  return `THIRD-PARTY SOFTWARE NOTICES

This file covers packages whose code contributes bytes to the Mermaid browser
bundle generated by Inkpath. Inkpath generated it from the exact esbuild bundle
metadata and package installations used for this site build.

The packages below remain subject to their respective license terms.

${sections.join("\n\n")}
`;
}
